### ISSUE TITLE
Convertire flag attivo in id_stato

### ISSUE THREAD

**Issue by GaetanoBlasa** [GaetanoBlasa/ea.app#12]
Convertire nelle tabelle che identificano entita il campo attivo in id_stato, che viene prelevato dall'array data.

**Comment by GiulianoDiVita** [comment]
Tabelle:
-Utenti
-Shop
-Advertiser
-Album
-App_partner
-Attributi_facilities
-Attributi_facilities_categoria
-Attributi_set_recapiti

**Comment by GiulianoDiVita** [comment]
Tabelle convertite:
-Utenti
-Shop
-Advertiser
-Album
-Attributi_set_recapiti
